
title: "Trail of Cthulhu - Red Tide Rising"
email: bescott@andrew.cmu.edu
url: "bescott.org/"
baseurl: "/trail-of-cthulhu"
permalink: /:title/

incremental: true

excerpt_separator: ___

kramdown:
  input: GFM
  auto_ids: true

gems:
- jekyll-redirect-from
- jekyll-coffeescript

whitelist:
- jekyll-redirect-from
- jekyll-coffeescript

description: >
  A Lovecraftian horror story,
  written for the Trail of Cthulhu Game System.


