
title: "Trail of Cthulhu : Red Tide Rising"
email: bescott@andrew.cmu.edu
url: "bescott.org/"
baseurl: "/trail-of-cthulhu"
permalink: /:title/
description: >
  A Lovecraftian horror story,
  written for the Trail of Cthulhu Game System.

gems:
#- jekyll-redirect-from
- jekyll-coffeescript
